name: build react list web
run-name: build react list web
on:
  push:
    branches:
      - main
jobs:
  docker_login:
    runs-on: ubuntu-latest
    name: build react list web
    steps:
      - name: code checkout
        uses: actions/checkout@v4.2.2

      - name: build
        run: |
          echo ${GITHUB_RUN_NUMBER}
          echo $(pwd)
          npm install -g typescript
          npm install --ignore-scripts && npm run build
          docker build . -t 169533462518.dkr.ecr.us-east-2.amazonaws.com/react-list-web:1.0.${GITHUB_RUN_NUMBER}
          docker image ls

      - name: docker login
        run: |
          val=$(AWS_ACCESS_KEY_ID=${{secrets.DOCKER_AWS_KEY}} AWS_SECRET_ACCESS_KEY=${{secrets.DOCKER_AWS_SECRET}} aws ecr get-login-password --region us-east-2)
          echo "val=$val" >> $GITHUB_ENV
          echo $val | docker login --username AWS --password-stdin 169533462518.dkr.ecr.us-east-2.amazonaws.com
          docker image ls

      - name: docker push
        run: |
          docker image push 169533462518.dkr.ecr.us-east-2.amazonaws.com/react-list-web:1.0.${GITHUB_RUN_NUMBER}
          echo docker pushed successfully


      - run: echo ${GITHUB_RUN_NUMBER}
      - run: echo $(pwd)
      - run: npm install -g typescript
      - run: npm install --ignore-scripts && npm run build
      - run: docker build . -t 169533462518.dkr.ecr.us-east-2.amazonaws.com/react-list-web:1.0.${GITHUB_RUN_NUMBER}
      - run: docker image ls

